# Generated by Django 4.2.29 on 2026-04-07 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分组名称")),
                ("code", models.CharField(max_length=50, verbose_name="分组代码")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("script", "脚本分组"),
                            ("action_set", "动作集合分组"),
                            ("task", "任务分组"),
                        ],
                        max_length=20,
                        verbose_name="分组类型",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="core.group",
                        verbose_name="父分组",
                    ),
                ),
            ],
            options={
                "verbose_name": "分组",
                "verbose_name_plural": "分组",
                "ordering": ["type", "order", "name"],
                "unique_together": {("code", "type")},
            },
        ),
    ]
