# Generated by Django 4.2.29 on 2026-04-07 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ElementLocator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="元素名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="元素代码"
                    ),
                ),
                (
                    "locator_type",
                    models.CharField(
                        choices=[
                            ("css", "CSS选择器"),
                            ("xpath", "XPath"),
                            ("id", "ID"),
                            ("name", "Name属性"),
                            ("class_name", "Class名称"),
                            ("tag_name", "标签名"),
                            ("text", "文本内容"),
                            ("role", "ARIA角色"),
                            ("test_id", "Test ID"),
                            ("placeholder", "Placeholder"),
                            ("label", "Label文本"),
                        ],
                        default="css",
                        max_length=20,
                        verbose_name="定位类型",
                    ),
                ),
                (
                    "locator_value",
                    models.CharField(max_length=500, verbose_name="定位值"),
                ),
                (
                    "page_url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="所在页面URL",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "wait_timeout",
                    models.IntegerField(default=10000, verbose_name="等待超时(毫秒)"),
                ),
                (
                    "wait_state",
                    models.CharField(
                        choices=[
                            ("visible", "可见"),
                            ("hidden", "隐藏"),
                            ("attached", "附加到DOM"),
                            ("detached", "从DOM分离"),
                        ],
                        default="visible",
                        max_length=20,
                        verbose_name="等待状态",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "元素定位器",
                "verbose_name_plural": "元素定位器",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TestScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="脚本名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="脚本代码"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("published", "已发布"),
                            ("archived", "已归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("version", models.IntegerField(default=1, verbose_name="版本号")),
                (
                    "target_url",
                    models.URLField(max_length=500, verbose_name="目标网站URL"),
                ),
                (
                    "script_data",
                    models.JSONField(default=dict, verbose_name="脚本数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scripts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_scripts",
                        to="products.producttype",
                        verbose_name="产品类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试脚本",
                "verbose_name_plural": "测试脚本",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TestStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="步骤名称")),
                ("order", models.IntegerField(default=0, verbose_name="执行顺序")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("navigate", "导航到URL"),
                            ("click", "点击元素"),
                            ("fill", "填充输入框"),
                            ("select", "选择下拉选项"),
                            ("check", "勾选复选框"),
                            ("uncheck", "取消勾选"),
                            ("wait", "等待"),
                            ("wait_for_selector", "等待元素"),
                            ("screenshot", "截图"),
                            ("scroll", "滚动"),
                            ("hover", "悬停"),
                            ("focus", "聚焦"),
                            ("press", "按键"),
                            ("upload", "上传文件"),
                            ("assert_text", "断言文本"),
                            ("assert_visible", "断言可见"),
                            ("assert_value", "断言值"),
                            ("custom", "自定义操作"),
                        ],
                        max_length=30,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "action_value",
                    models.TextField(blank=True, default="", verbose_name="操作值"),
                ),
                (
                    "action_config",
                    models.JSONField(default=dict, verbose_name="操作配置"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "continue_on_failure",
                    models.BooleanField(default=False, verbose_name="失败时继续"),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="重试次数"),
                ),
                (
                    "retry_interval",
                    models.IntegerField(default=1000, verbose_name="重试间隔(毫秒)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "element",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_steps",
                        to="script_editor.elementlocator",
                        verbose_name="目标元素",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="script_editor.testscript",
                        verbose_name="测试脚本",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试步骤",
                "verbose_name_plural": "测试步骤",
                "ordering": ["order"],
                "unique_together": {("script", "order")},
            },
        ),
        migrations.CreateModel(
            name="ScriptVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.IntegerField(verbose_name="版本号")),
                ("script_data", models.JSONField(verbose_name="脚本数据")),
                (
                    "change_note",
                    models.TextField(blank=True, default="", verbose_name="变更说明"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="script_editor.testscript",
                        verbose_name="脚本",
                    ),
                ),
            ],
            options={
                "verbose_name": "脚本版本",
                "verbose_name_plural": "脚本版本",
                "ordering": ["-version_number"],
                "unique_together": {("script", "version_number")},
            },
        ),
    ]
