# Generated by Django 4.2.29 on 2026-04-07 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("script_editor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="动作集合名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="动作集合代码"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("input", "输入操作"),
                            ("navigation", "导航操作"),
                            ("form", "表单操作"),
                            ("validation", "验证操作"),
                            ("general", "通用操作"),
                        ],
                        default="general",
                        max_length=100,
                        verbose_name="分类",
                    ),
                ),
                (
                    "is_builtin",
                    models.BooleanField(default=False, verbose_name="是否内置"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_sets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "动作集合",
                "verbose_name_plural": "动作集合",
                "ordering": ["category", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="testscript",
            name="product_type",
        ),
        migrations.AddField(
            model_name="teststep",
            name="action_set_params",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="动作集合参数"
            ),
        ),
        migrations.AlterField(
            model_name="teststep",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("navigate", "导航到URL"),
                    ("click", "点击元素"),
                    ("fill", "填充输入框"),
                    ("select", "选择下拉选项"),
                    ("check", "勾选复选框"),
                    ("uncheck", "取消勾选"),
                    ("wait", "等待"),
                    ("wait_for_selector", "等待元素"),
                    ("screenshot", "截图"),
                    ("scroll", "滚动"),
                    ("hover", "悬停"),
                    ("focus", "聚焦"),
                    ("press", "按键"),
                    ("upload", "上传文件"),
                    ("assert_text", "断言文本"),
                    ("assert_visible", "断言可见"),
                    ("assert_value", "断言值"),
                    ("action_set", "动作集合"),
                    ("custom", "自定义操作"),
                ],
                max_length=30,
                verbose_name="操作类型",
            ),
        ),
        migrations.AddField(
            model_name="teststep",
            name="action_set_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_steps",
                to="script_editor.actionset",
                verbose_name="动作集合",
            ),
        ),
        migrations.CreateModel(
            name="ActionSetStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="步骤名称")),
                ("order", models.IntegerField(default=0, verbose_name="执行顺序")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("click", "点击元素"),
                            ("fill", "填充输入框"),
                            ("select", "选择下拉选项"),
                            ("check", "勾选复选框"),
                            ("uncheck", "取消勾选"),
                            ("wait", "等待"),
                            ("wait_for_selector", "等待元素"),
                            ("scroll", "滚动"),
                            ("hover", "悬停"),
                            ("focus", "聚焦"),
                            ("press", "按键"),
                            ("assert_text", "断言文本"),
                            ("assert_visible", "断言可见"),
                        ],
                        max_length=30,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "locator_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("css", "CSS选择器"),
                            ("xpath", "XPath"),
                            ("id", "ID"),
                            ("name", "Name属性"),
                            ("class_name", "Class名称"),
                            ("text", "文本内容"),
                            ("placeholder", "Placeholder"),
                            ("label", "Label文本"),
                        ],
                        default="css",
                        max_length=20,
                        verbose_name="定位类型",
                    ),
                ),
                (
                    "locator_value",
                    models.CharField(
                        blank=True, default="", max_length=500, verbose_name="定位值"
                    ),
                ),
                (
                    "locator_description",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="定位描述"
                    ),
                ),
                (
                    "action_value",
                    models.TextField(blank=True, default="", verbose_name="操作值"),
                ),
                (
                    "action_value_type",
                    models.CharField(
                        choices=[
                            ("static", "静态值"),
                            ("parameter", "参数"),
                            ("expression", "表达式"),
                        ],
                        default="static",
                        max_length=20,
                        verbose_name="值类型",
                    ),
                ),
                (
                    "parameter_name",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="参数名称"
                    ),
                ),
                (
                    "wait_timeout",
                    models.IntegerField(default=10000, verbose_name="等待超时(ms)"),
                ),
                (
                    "continue_on_failure",
                    models.BooleanField(default=False, verbose_name="失败时继续"),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="重试次数"),
                ),
                (
                    "retry_interval",
                    models.IntegerField(default=1000, verbose_name="重试间隔(ms)"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "action_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="script_editor.actionset",
                        verbose_name="动作集合",
                    ),
                ),
            ],
            options={
                "verbose_name": "动作集合步骤",
                "verbose_name_plural": "动作集合步骤",
                "ordering": ["order"],
                "unique_together": {("action_set", "order")},
            },
        ),
        migrations.CreateModel(
            name="ActionSetParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="参数名称")),
                ("code", models.CharField(max_length=50, verbose_name="参数代码")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "default_value",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="默认值"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="是否必填"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "action_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="script_editor.actionset",
                        verbose_name="动作集合",
                    ),
                ),
            ],
            options={
                "verbose_name": "动作集合参数",
                "verbose_name_plural": "动作集合参数",
                "ordering": ["order"],
                "unique_together": {("action_set", "code")},
            },
        ),
    ]
