# Generated by Django 4.2.29 on 2026-04-07 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0002_add_actionset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teststep",
            name="action_set_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_steps_ref",
                to="script_editor.actionset",
                verbose_name="动作集合",
            ),
        ),
    ]
