# Generated by Django 4.2.29 on 2026-04-07 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("script_editor", "0003_update_actionset_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionset",
            name="group",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "action_set"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_sets",
                to="core.group",
                verbose_name="分组",
            ),
        ),
        migrations.AddField(
            model_name="testscript",
            name="group",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "script"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scripts",
                to="core.group",
                verbose_name="分组",
            ),
        ),
    ]
