# Generated by Django 4.2.29 on 2026-04-08 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0004_actionset_group_testscript_group"),
    ]

    operations = []
