# Generated by Django 4.2.29 on 2026-04-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0006_add_random_options_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionsetstep",
            name="random_options",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="随机选项列表"
            ),
        ),
        migrations.AddField(
            model_name="actionsetstep",
            name="select_mode",
            field=models.CharField(
                choices=[("dropdown", "下拉框选择"), ("click", "点击卡片")],
                default="dropdown",
                max_length=20,
                verbose_name="选择模式",
            ),
        ),
        migrations.AlterField(
            model_name="actionsetstep",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("click", "点击元素"),
                    ("fill", "填充输入框"),
                    ("select", "选择下拉选项"),
                    ("random_select", "随机选择"),
                    ("check", "勾选复选框"),
                    ("uncheck", "取消勾选"),
                    ("wait", "等待"),
                    ("wait_for_selector", "等待元素"),
                    ("scroll", "滚动"),
                    ("hover", "悬停"),
                    ("focus", "聚焦"),
                    ("press", "按键"),
                    ("assert_text", "断言文本"),
                    ("assert_visible", "断言可见"),
                ],
                max_length=30,
                verbose_name="操作类型",
            ),
        ),
    ]
