# Generated by Django 4.2.29 on 2026-04-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0007_add_actionset_random_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionsetstep",
            name="random_max",
            field=models.IntegerField(
                blank=True, default=100, null=True, verbose_name="随机数最大值"
            ),
        ),
        migrations.AddField(
            model_name="actionsetstep",
            name="random_min",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="随机数最小值"
            ),
        ),
        migrations.AlterField(
            model_name="actionsetstep",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("click", "点击元素"),
                    ("fill", "填充输入框"),
                    ("select", "选择下拉选项"),
                    ("random_select", "随机选择"),
                    ("random_number", "随机数值"),
                    ("check", "勾选复选框"),
                    ("uncheck", "取消勾选"),
                    ("wait", "等待"),
                    ("wait_for_selector", "等待元素"),
                    ("scroll", "滚动"),
                    ("hover", "悬停"),
                    ("focus", "聚焦"),
                    ("press", "按键"),
                    ("assert_text", "断言文本"),
                    ("assert_visible", "断言可见"),
                ],
                max_length=30,
                verbose_name="操作类型",
            ),
        ),
        migrations.AlterField(
            model_name="teststep",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("navigate", "导航到URL"),
                    ("click", "点击元素"),
                    ("fill", "填充输入框"),
                    ("select", "选择下拉选项"),
                    ("random_select", "随机选择"),
                    ("random_number", "随机数值"),
                    ("check", "勾选复选框"),
                    ("uncheck", "取消勾选"),
                    ("wait", "等待"),
                    ("wait_for_selector", "等待元素"),
                    ("screenshot", "截图"),
                    ("scroll", "滚动"),
                    ("hover", "悬停"),
                    ("focus", "聚焦"),
                    ("press", "按键"),
                    ("upload", "上传文件"),
                    ("assert_text", "断言文本"),
                    ("assert_visible", "断言可见"),
                    ("assert_value", "断言值"),
                    ("action_set", "动作集合"),
                    ("custom", "自定义操作"),
                ],
                max_length=30,
                verbose_name="操作类型",
            ),
        ),
    ]
