# Generated by Django 4.2.29 on 2026-04-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0008_add_random_number_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionsetstep",
            name="force_click",
            field=models.BooleanField(default=False, verbose_name="强制点击"),
        ),
    ]
