# Generated by Django 4.2.29 on 2026-04-08 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("script_editor", "0009_add_force_click_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headless_mode",
                    models.BooleanField(
                        default=False, verbose_name="无头模式（不显示浏览器）"
                    ),
                ),
                (
                    "default_timeout",
                    models.IntegerField(
                        default=30000, verbose_name="默认超时时间(毫秒)"
                    ),
                ),
                (
                    "step_screenshot",
                    models.BooleanField(
                        default=False,
                        help_text="是否在每个步骤执行后截取操作元素的截图",
                        verbose_name="每步截图",
                    ),
                ),
                (
                    "slow_mo",
                    models.IntegerField(
                        default=0,
                        help_text="每个操作之间的延迟时间",
                        verbose_name="操作延迟(毫秒)",
                    ),
                ),
                (
                    "viewport_width",
                    models.IntegerField(default=1920, verbose_name="视口宽度"),
                ),
                (
                    "viewport_height",
                    models.IntegerField(default=1080, verbose_name="视口高度"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "全局配置",
                "verbose_name_plural": "全局配置",
            },
        ),
    ]
