# Generated by Django 4.2.29 on 2026-04-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0010_add_global_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfig",
            name="scroll_direction",
            field=models.CharField(
                choices=[
                    ("down", "向下"),
                    ("up", "向上"),
                    ("left", "向左"),
                    ("right", "向右"),
                ],
                default="down",
                max_length=10,
                verbose_name="默认滚动方向",
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="scroll_distance",
            field=models.IntegerField(default=500, verbose_name="默认滚动距离(像素)"),
        ),
    ]
