# Generated by Django 4.2.29 on 2026-04-14 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0011_globalconfig_scroll_direction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teststep",
            name="locator_type",
            field=models.CharField(blank=True, default="css", max_length=20),
        ),
        migrations.AddField(
            model_name="teststep",
            name="locator_value",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
