# Generated by Django 4.2.29 on 2026-04-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0012_teststep_locator_type_teststep_locator_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teststep",
            name="locator_type",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="定位类型"
            ),
        ),
        migrations.AlterField(
            model_name="teststep",
            name="locator_value",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="定位值"
            ),
        ),
    ]
