# Generated by Django 6.0.3 on 2026-04-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0013_alter_teststep_locator_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teststep",
            name="locator_type",
        ),
        migrations.RemoveField(
            model_name="teststep",
            name="locator_value",
        ),
    ]
