# Generated by Django 6.0.3 on 2026-04-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0014_remove_teststep_locator_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionsetstep",
            name="action_config",
            field=models.JSONField(blank=True, default=dict, verbose_name="操作配置"),
        ),
    ]
