# Generated by Django 6.0.3 on 2026-04-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0015_add_actionsetstep_action_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfig",
            name="log_level",
            field=models.CharField(
                choices=[
                    ("DEBUG", "DEBUG"),
                    ("INFO", "INFO"),
                    ("WARNING", "WARNING"),
                    ("ERROR", "ERROR"),
                ],
                default="INFO",
                help_text="控制终端输出的日志详细程度",
                max_length=10,
                verbose_name="终端日志等级",
            ),
        ),
    ]
