# Generated by Django 6.0.3 on 2026-04-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0016_globalconfig_log_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalconfig",
            name="log_level",
            field=models.CharField(
                choices=[
                    ("DEBUG", "DEBUG - 全部日志"),
                    ("INFO", "INFO - 常规日志"),
                    ("WARNING", "WARNING - 警告日志"),
                    ("ERROR", "ERROR - 仅错误日志"),
                ],
                default="DEBUG",
                help_text="控制终端输出的日志详细程度，DEBUG为最详细",
                max_length=10,
                verbose_name="终端日志等级",
            ),
        ),
    ]
