# Generated by Django 6.0.3 on 2026-04-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0017_add_globalconfig_log_level_v2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalconfig",
            name="log_level",
            field=models.CharField(
                choices=[
                    ("DEBUG", "DEBUG (调试)"),
                    ("INFO", "INFO (信息)"),
                    ("WARNING", "WARNING (警告)"),
                    ("ERROR", "ERROR (错误)"),
                ],
                default="DEBUG",
                help_text="控制台输出的日志级别，DEBUG 显示所有日志",
                max_length=10,
                verbose_name="终端日志级别",
            ),
        ),
    ]
