# Generated by Django 6.0.3 on 2026-04-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0018_alter_globalconfig_log_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalconfig",
            name="log_level",
            field=models.CharField(
                choices=[
                    ("DEBUG", "DEBUG - 详细调试"),
                    ("INFO", "INFO - 一般信息"),
                    ("WARNING", "WARNING - 警告"),
                    ("ERROR", "ERROR - 错误"),
                    ("CRITICAL", "CRITICAL - 严重错误"),
                ],
                default="DEBUG",
                max_length=20,
                verbose_name="日志等级",
            ),
        ),
    ]
