# Generated by Django 6.0.3 on 2026-04-22 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0019_alter_globalconfig_log_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="globalconfig",
            name="log_level",
        ),
    ]
