# Generated by Django 6.0.3 on 2026-04-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0020_remove_globalconfig_log_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfig",
            name="marketplace_api_url",
            field=models.CharField(
                default="http://127.0.0.1:8000",
                help_text="集合文件的来源API地址",
                max_length=500,
                verbose_name="集合文件API地址",
            ),
        ),
    ]
