# Generated by Django 6.0.3 on 2026-04-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0021_globalconfig_marketplace_api_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfig",
            name="management_platform_url",
            field=models.CharField(
                default="http://localhost:8001/api/script-results/upload",
                help_text="脚本执行结果上传的目标地址",
                max_length=500,
                verbose_name="自动化管理平台API地址",
            ),
        ),
    ]
