# Generated by Django 6.0.3 on 2026-04-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0022_add_management_platform_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfig",
            name="username",
            field=models.CharField(
                blank=True,
                default="",
                help_text="用于标识上传的任务结果报告",
                max_length=100,
                verbose_name="用户名",
            ),
        ),
    ]
