# Generated by Django 6.0.3 on 2026-04-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0023_globalconfig_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfig",
            name="email_enable",
            field=models.BooleanField(
                default=False,
                help_text="是否启用邮件发送功能",
                verbose_name="启用邮件通知",
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="email_password",
            field=models.CharField(
                blank=True,
                default="",
                help_text="邮箱密码或授权码",
                max_length=200,
                verbose_name="邮箱密码/授权码",
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="email_recipients",
            field=models.CharField(
                blank=True,
                default="",
                help_text="收件人邮箱，多个用逗号分隔",
                max_length=1000,
                verbose_name="收件人列表",
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="email_smtp_host",
            field=models.CharField(
                blank=True,
                default="",
                help_text="邮件发送服务器地址，如smtp.qq.com",
                max_length=200,
                verbose_name="SMTP服务器地址",
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="email_smtp_port",
            field=models.IntegerField(
                default=465,
                help_text="SMTP服务器端口，SSL通常为465，STARTTLS通常为587",
                verbose_name="SMTP端口",
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="email_use_ssl",
            field=models.BooleanField(
                default=True,
                help_text="是否使用SSL连接（通常465端口使用SSL，587端口不使用）",
                verbose_name="使用SSL连接",
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="email_username",
            field=models.CharField(
                blank=True,
                default="",
                help_text="用于发送邮件的邮箱地址",
                max_length=200,
                verbose_name="发件人邮箱",
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="report_base_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="任务结果报告的访问地址前缀，用于邮件中的报告链接",
                max_length=500,
                verbose_name="报告访问地址",
            ),
        ),
    ]
