# Generated by Django 4.2.29 on 2026-04-07 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("script_editor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("parameters", models.JSONField(default=dict, verbose_name="测试参数")),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="计划执行时间"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Celery任务ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="script_editor.testscript",
                        verbose_name="测试脚本",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试任务",
                "verbose_name_plural": "测试任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_name",
                    models.CharField(max_length=200, verbose_name="步骤名称"),
                ),
                ("step_order", models.IntegerField(verbose_name="步骤顺序")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("passed", "通过"),
                            ("failed", "失败"),
                            ("skipped", "跳过"),
                            ("error", "错误"),
                        ],
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("duration", models.FloatField(default=0, verbose_name="执行时长(秒)")),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "error_stack",
                    models.TextField(blank=True, default="", verbose_name="错误堆栈"),
                ),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="screenshots/",
                        verbose_name="截图",
                    ),
                ),
                ("logs", models.JSONField(default=list, verbose_name="执行日志")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="test_manager.testtask",
                        verbose_name="测试任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试结果",
                "verbose_name_plural": "测试结果",
                "ordering": ["step_order"],
            },
        ),
        migrations.CreateModel(
            name="TestReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_steps",
                    models.IntegerField(default=0, verbose_name="总步骤数"),
                ),
                (
                    "passed_steps",
                    models.IntegerField(default=0, verbose_name="通过步骤数"),
                ),
                (
                    "failed_steps",
                    models.IntegerField(default=0, verbose_name="失败步骤数"),
                ),
                (
                    "skipped_steps",
                    models.IntegerField(default=0, verbose_name="跳过步骤数"),
                ),
                (
                    "total_duration",
                    models.FloatField(default=0, verbose_name="总执行时长(秒)"),
                ),
                ("summary", models.JSONField(default=dict, verbose_name="汇总数据")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="test_manager.testtask",
                        verbose_name="测试任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试报告",
                "verbose_name_plural": "测试报告",
            },
        ),
    ]
