# Generated by Django 4.2.29 on 2026-04-07 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("script_editor", "0004_actionset_group_testscript_group"),
        ("core", "0001_initial"),
        ("test_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregateTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="聚合任务名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("partial", "部分成功"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="计划执行时间"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Celery任务ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aggregate_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "task"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aggregate_tasks",
                        to="core.group",
                        verbose_name="分组",
                    ),
                ),
            ],
            options={
                "verbose_name": "聚合任务",
                "verbose_name_plural": "聚合任务",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="testtask",
            name="group",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "task"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_tasks",
                to="core.group",
                verbose_name="分组",
            ),
        ),
        migrations.CreateModel(
            name="AggregateTaskItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="执行顺序")),
                ("parameters", models.JSONField(default=dict, verbose_name="测试参数")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("skipped", "跳过"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "aggregate_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="test_manager.aggregatetask",
                        verbose_name="聚合任务",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggregate_items",
                        to="script_editor.testscript",
                        verbose_name="测试脚本",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aggregate_item",
                        to="test_manager.testtask",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "聚合任务项",
                "verbose_name_plural": "聚合任务项",
                "ordering": ["order"],
                "unique_together": {("aggregate_task", "order")},
            },
        ),
    ]
