# Generated by Django 4.2.29 on 2026-04-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0002_aggregatetask_testtask_group_aggregatetaskitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="action_values",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="存储步骤执行时的操作值，如输入值、随机选择的值等",
                verbose_name="操作值",
            ),
        ),
    ]
