# Generated by Django 6.0.3 on 2026-04-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0003_add_action_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="testtask",
            name="is_aggregate_subtask",
            field=models.BooleanField(
                default=False,
                help_text="标记此任务是否由聚合任务创建的子任务",
                verbose_name="是否为聚合任务子任务",
            ),
        ),
    ]
