# Generated by Django 6.0.3 on 2026-04-22 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0005_taskgroup_and_taskgroupitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aggregatetaskitem",
            name="aggregate_task",
        ),
        migrations.AlterUniqueTogether(
            name="aggregatetaskitem",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="aggregatetaskitem",
            name="script",
        ),
        migrations.RemoveField(
            model_name="aggregatetaskitem",
            name="task",
        ),
        migrations.DeleteModel(
            name="AggregateTask",
        ),
        migrations.DeleteModel(
            name="AggregateTaskItem",
        ),
    ]
