# Generated by Django 6.0.3 on 2026-04-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0006_cleanup_aggregate_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="testtask",
            name="task_batch_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="用于将多个脚本任务分组为一次批量执行的批次",
                max_length=36,
                verbose_name="任务批次ID",
            ),
        ),
    ]
