# Generated by Django 6.0.3 on 2026-04-22 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("script_editor", "0020_remove_globalconfig_log_level"),
        ("test_manager", "0007_testtask_task_batch_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testtask",
            name="task_batch_id",
        ),
        migrations.AlterField(
            model_name="testtask",
            name="script",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="script_editor.testscript",
                verbose_name="主测试脚本",
            ),
        ),
        migrations.CreateModel(
            name="TaskScript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="执行顺序")),
                (
                    "parameters",
                    models.JSONField(blank=True, default=dict, verbose_name="测试参数"),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_scripts",
                        to="script_editor.testscript",
                        verbose_name="测试脚本",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_scripts",
                        to="test_manager.testtask",
                        verbose_name="测试任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务脚本",
                "verbose_name_plural": "任务脚本",
                "ordering": ["order"],
                "unique_together": {("task", "script")},
            },
        ),
    ]
