# Generated by Django 6.0.3 on 2026-04-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "test_manager",
            "0008_remove_testtask_task_batch_id_alter_testtask_script_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="testtask",
            name="upload_status",
            field=models.CharField(
                choices=[
                    ("none", "未上传"),
                    ("uploading", "上传中"),
                    ("uploaded", "已上传"),
                    ("failed", "上传失败"),
                    ("pending", "待上传"),
                ],
                default="none",
                help_text="结果上传到JSON管理平台的状态",
                max_length=20,
                verbose_name="上传状态",
            ),
        ),
    ]
