# Generated by Django 6.0.3 on 2026-04-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_manager", "0010_add_upload_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="testtask",
            name="send_email",
            field=models.BooleanField(
                default=False,
                help_text="勾选后任务完成后自动发送邮件通知",
                verbose_name="是否发送邮件通知",
            ),
        ),
    ]
