# Generated by Django 4.2.29 on 2026-04-07 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="产品类型名称"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="产品类型代码"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product_icons/",
                        verbose_name="图标",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "产品类型",
                "verbose_name_plural": "产品类型",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="参数名称")),
                ("code", models.CharField(max_length=50, verbose_name="参数代码")),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("text", "文本输入"),
                            ("select", "下拉选择"),
                            ("radio", "单选按钮"),
                            ("checkbox", "复选框"),
                            ("number", "数字输入"),
                            ("color", "颜色选择"),
                            ("file", "文件上传"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="输入类型",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="是否必填"),
                ),
                (
                    "default_value",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="默认值"
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="占位提示"
                    ),
                ),
                (
                    "validation_regex",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="验证正则"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="products.producttype",
                        verbose_name="产品类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品参数",
                "verbose_name_plural": "产品参数",
                "ordering": ["order", "name"],
                "unique_together": {("product_type", "code")},
            },
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_value",
                    models.CharField(max_length=100, verbose_name="显示值"),
                ),
                (
                    "actual_value",
                    models.CharField(max_length=255, verbose_name="实际值"),
                ),
                (
                    "price_modifier",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="价格调整",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="products.productparameter",
                        verbose_name="参数",
                    ),
                ),
            ],
            options={
                "verbose_name": "参数选项",
                "verbose_name_plural": "参数选项",
                "ordering": ["order", "display_value"],
            },
        ),
    ]
